name: google_map_polyline_new
description: Gives the polyline coordinates to set polylines in Google Map.
version: 0.3.0+2
homepage: https://github.com/yusriltakeuchi/google_map_polyline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
